osx_image: xcode7
language: objective-c
before_install:
  - gem install cocoapods --no-document
  - gem install xcpretty --no-document
  - cd Example\ Project
script:
  - xcodebuild -workspace PWProgressView.xcworkspace -scheme PWProgressView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -workspace PWProgressView.xcworkspace -scheme PWProgressView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
