osx_image: xcode7
language: objective-c
before_install:
  - gem install cocoapods --no-document
  - gem install xcpretty --no-document
  - pod install --project-directory=Example\ Project
script:
  - set -o pipefail && xcodebuild test -workspace Example\ Project/PWProgressView.xcworkspace -scheme PWProgressView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - pod lib lint --quick
